# Generated by Django 5.0.6 on 2024-06-06 18:07

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_alter_portfolio_basic_information_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Phone (+880..........)'),
        ),
    ]
