# Generated by Django 5.0.6 on 2024-06-09 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_alter_portfolio_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='hobbies',
            new_name='reference',
        ),
    ]
